name: Build software for ESP32 and ESP8266
on:
  pull_request:
    types: [opened, reopened]
  push:
  workflow_dispatch:
jobs:
  pre_job:
    runs-on: ubuntu-latest
    # If we push a commit with a new tag, it triggers two workflows.
    #  one for the new commit, one for the new tag.
    # This detects if multiple concurrent workflows are running.
    outputs:
      concurrent_workflows: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'always'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  build:
    needs: pre_job
    # If there are current workflows running, we want to run the one with the tag.
    # Therefore, the other workflow(s) are skipped.
    if: needs.pre_job.outputs.concurrent_workflows == 'false' || (needs.pre_job.outputs.concurrent_workflows == 'true' && github.ref_type == 'tag')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [esp32dev, esp8266dev, spa-control-pcb]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ matrix.platform }}-${{ hashFiles('**/platformio.ini', '**/lib_deps/*') }}
          restore-keys: |
            ${{ runner.os }}-platformio-${{ matrix.platform }}-
      - name: Cache PlatformIO Build Directory
        uses: actions/cache@v4
        with:
          path: .pio
          key: ${{ runner.os }}-pio-${{ matrix.platform }}-${{ hashFiles('**/platformio.ini', '**/lib_deps/*') }}
          restore-keys: |
            ${{ runner.os }}-pio-${{ matrix.platform }}-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build for ${{ matrix.platform }}
        run: pio run -e ${{ matrix.platform }} -t mergebin
      #- name: Display firmware files
      #  run: ls -la .pio/build/${{ matrix.platform }}/firmware*.bin
      - name: Rename and move firmware files
        run: |
          mv .pio/build/${{ matrix.platform }}/firmware.bin firmware_${{ matrix.platform }}_ota.bin
          if [ "${{ matrix.platform }}" != "esp8266dev" ]; then
            mv .pio/build/${{ matrix.platform }}/firmware_factory.bin firmware_${{ matrix.platform }}_factory.bin
          fi
          ls -la firmware*.bin
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware_${{ matrix.platform }}
          path: firmware_${{ matrix.platform }}*.bin

  release:
    name: Release
    # Optionally limit releases to the mast branch. We might want beta releases from other branches.
    #if: startsWith(github.event.ref, 'refs/tags/v') && github.ref == 'refs/heads/master'
    # Create a release if we have a tag that starts with v. E.g. v0.1.0 or v0.1.1-beta
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for CHANGELOG
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware
          merge-multiple: true
      #- name: Display structure of downloaded files
      #  run: ls -Rla firmware/
      # New release uses the tag as the release name and CHANGELOG.md as the body.
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "firmware/firmware*.bin"
          bodyFile: "CHANGELOG.md"
          removeArtifacts: true
